package com.jtig.euler.problem.impl;

import com.jtig.euler.problem.Problem;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * <pre>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * </pre>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem2 implements Problem {
    @Override
    public String getName() {
        return "Even Fibonacci numbers";
    }

    @Override
    public String getDescription() {
        return "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n" +
                "\n" +
                "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n" +
                "\n" +
                "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";
    }

    @Override
    public Number getResult() {
        long sum = 0;
        long first = 1;
        long second = 1;
        while(second < 4000000) {
            if (second %2 == 0) {
                sum += second;
            }
            long tmp = second;
            second += first;
            first = tmp;
        }

        System.out.println("Problem 2: " + sum);
        return sum;
    }

    @Override
    public boolean getSolved() {
        return true;
    }
}
